WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 30, in songs
    return render(request, 'PumpManager/songs.html', {'songs': songs[0][0]})
TypeError: 'function' object is not subscriptable
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 30, in songs
    return render(request, 'PumpManager/songs.html', {'songs': songs[0][0]})
TypeError: 'function' object is not subscriptable
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 36, in songs
    return render(request, 'PumpManager/songs.html', {'songs': songs[0]})
TypeError: 'function' object is not subscriptable
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 36, in songs
    return render(request, 'PumpManager/songs.html', {'songs': songs[0][0]})
TypeError: 'function' object is not subscriptable
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 36, in songs
    word = songs[0][0]
TypeError: 'function' object is not subscriptable
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 70, in songs
    return render(request, 'PumpManager/songs.html', {'songs': Song.objects.all()})
NameError: name 'Song' is not defined
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /lists/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 68, in songs
    return render(request, 'yourapp/output.html', {'songs': "asd"})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: yourapp/output.html
WARNING:HttpError
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /songs/pricing.css
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:Not Found: /pl
WARNING:HttpError
ERROR:Internal Server Error: /songs/1
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 78, in songID
    return render(request, 'PumpManager/songID.html', {'song': song})
NameError: name 'song' is not defined
WARNING:HttpError
ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 75, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 76, in songID
    except Question.DoesNotExist:
NameError: name 'Question' is not defined
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 75, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 76, in songID
    except Question.DoesNotExist:
NameError: name 'Question' is not defined
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 75, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 76, in songID
    except Question.DoesNotExist:
NameError: name 'Question' is not defined
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
ERROR:Internal Server Error: /songs/6
Traceback (most recent call last):
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 75, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
PumpManager.models.Song.DoesNotExist: Song matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 76, in songID
    except Question.DoesNotExist:
NameError: name 'Question' is not defined
WARNING:HttpError
ERROR:Internal Server Error: /songs/6
Traceback (most recent call last):
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 75, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
PumpManager.models.Song.DoesNotExist: Song matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 77, in songID
    raise Http404("Song does not exist")
NameError: name 'Http404' is not defined
ERROR:Internal Server Error: /songs/6
Traceback (most recent call last):
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 75, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
PumpManager.models.Song.DoesNotExist: Song matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 77, in songID
    raise Http404("Song does not exist")
NameError: name 'Http404' is not defined
WARNING:HttpError
WARNING:Not Found: /songs/6
ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 76, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
2019-05-21 19:28:48,051; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 19:37:27,927; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 19:48:35,142; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 19:50:02,486; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 19:50:48,130; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 20:02:35,224; ERROR:Internal Server Error: /mixes/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 158, in mixes
    v = Version(mix = m, version = version)
NameError: name 'Version' is not defined
2019-05-21 20:10:50,699; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 20:11:47,022; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 20:16:36,767; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 20:18:36,847; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 20:21:20,022; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-21 20:21:40,605; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
WARNING:HttpError
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
WARNING:HttpError
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
WARNING:HttpError
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
WARNING:HttpError
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
WARNING:HttpError
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
WARNING:HttpError
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
ERROR:name 'chart' is not defined
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 119, in songs
    songs, charts = pumpdb.convertSongs()
  File "/home/chudik/dbproject/testproj/PumpManager/pumpdb.py", line 92, in convertSongs
    song['charts'] = charts[i]
IndexError: list index out of range
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 119, in songs
    songs, charts = pumpdb.convertSongs()
  File "/home/chudik/dbproject/testproj/PumpManager/pumpdb.py", line 91, in convertSongs
    song['cathegory'] = songs[i][j+6]
IndexError: list index out of range
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 119, in songs
    songs, charts = pumpdb.convertSongs()
ValueError: too many values to unpack (expected 2)
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 127, in songs
    s.save()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1288, in execute_sql
    for sql, params in self.as_sql():
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1241, in as_sql
    for obj in self.query.objs
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1241, in <listcomp>
    for obj in self.query.objs
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1240, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1182, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 1807, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'Stick'
WARNING:HttpError
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 128, in songs
    s.save()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1288, in execute_sql
    for sql, params in self.as_sql():
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1241, in as_sql
    for obj in self.query.objs
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1241, in <listcomp>
    for obj in self.query.objs
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1240, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1182, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 1807, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'Stick'
WARNING:Not Found: /favicon.ico
2019-05-24 23:06:35,636; ERROR:Internal Server Error: /mixes/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 235, in mixID
    {'mix': Mix.objects.get(pk=mix_id)})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
2019-05-24 23:06:35,694; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-24 23:09:08,450; ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 188, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
2019-05-24 23:09:08,456; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-24 23:09:55,453; ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 188, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
2019-05-24 23:09:55,461; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-24 23:10:26,552; ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 188, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
2019-05-24 23:10:26,559; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-24 23:10:29,100; ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 188, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
2019-05-24 23:10:29,107; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-24 23:10:40,171; ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 188, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
2019-05-24 23:10:40,177; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-24 23:10:49,037; ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 188, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
2019-05-24 23:10:49,043; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-24 23:10:49,928; ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 188, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
2019-05-24 23:10:49,934; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
2019-05-24 23:10:51,953; ERROR:Internal Server Error: /songs/pricing.css
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 188, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pricing.css'
2019-05-24 23:10:51,960; WARNING:Not Found: /docs/4.3/assets/brand/bootstrap-solid.svg
DEBUG:Start from server, version: 0.9, properties: {'product': 'RabbitMQ', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.', 'version': '3.5.7', 'capabilities': {'publisher_confirms': True, 'basic.nack': True, 'per_consumer_qos': True, 'authentication_failure_close': True, 'consumer_priorities': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'exchange_exchange_bindings': True}, 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'cluster_name': 'rabbit@chudik-K501UQ', 'platform': 'Erlang/OTP'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'platform': 'Erlang/OTP', 'version': '3.5.7', 'cluster_name': 'rabbit@chudik-K501UQ', 'capabilities': {'connection.blocked': True, 'basic.nack': True, 'authentication_failure_close': True, 'publisher_confirms': True, 'consumer_priorities': True, 'per_consumer_qos': True, 'exchange_exchange_bindings': True, 'consumer_cancel_notify': True}, 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'product': 'RabbitMQ'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'per_consumer_qos': True, 'consumer_cancel_notify': True, 'authentication_failure_close': True, 'basic.nack': True, 'consumer_priorities': True, 'connection.blocked': True}, 'version': '3.5.7', 'cluster_name': 'rabbit@chudik-K501UQ', 'product': 'RabbitMQ', 'platform': 'Erlang/OTP', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'cluster_name': 'rabbit@chudik-K501UQ', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'capabilities': {'consumer_cancel_notify': True, 'consumer_priorities': True, 'basic.nack': True, 'per_consumer_qos': True, 'exchange_exchange_bindings': True, 'authentication_failure_close': True, 'publisher_confirms': True, 'connection.blocked': True}, 'version': '3.5.7', 'platform': 'Erlang/OTP', 'product': 'RabbitMQ', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'capabilities': {'authentication_failure_close': True, 'connection.blocked': True, 'exchange_exchange_bindings': True, 'per_consumer_qos': True, 'publisher_confirms': True, 'consumer_cancel_notify': True, 'consumer_priorities': True, 'basic.nack': True}, 'platform': 'Erlang/OTP', 'cluster_name': 'rabbit@chudik-K501UQ', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.', 'product': 'RabbitMQ', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'version': '3.5.7'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'version': '3.5.7', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.', 'product': 'RabbitMQ', 'platform': 'Erlang/OTP', 'capabilities': {'consumer_cancel_notify': True, 'connection.blocked': True, 'basic.nack': True, 'authentication_failure_close': True, 'consumer_priorities': True, 'exchange_exchange_bindings': True, 'per_consumer_qos': True, 'publisher_confirms': True}, 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'cluster_name': 'rabbit@chudik-K501UQ'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'capabilities': {'consumer_priorities': True, 'consumer_cancel_notify': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'connection.blocked': True, 'publisher_confirms': True, 'basic.nack': True, 'exchange_exchange_bindings': True}, 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'version': '3.5.7', 'cluster_name': 'rabbit@chudik-K501UQ', 'product': 'RabbitMQ', 'platform': 'Erlang/OTP', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'product': 'RabbitMQ', 'capabilities': {'per_consumer_qos': True, 'consumer_cancel_notify': True, 'exchange_exchange_bindings': True, 'consumer_priorities': True, 'publisher_confirms': True, 'basic.nack': True, 'connection.blocked': True, 'authentication_failure_close': True}, 'version': '3.5.7', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'platform': 'Erlang/OTP', 'cluster_name': 'rabbit@chudik-K501UQ', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'cluster_name': 'rabbit@chudik-K501UQ', 'capabilities': {'per_consumer_qos': True, 'authentication_failure_close': True, 'connection.blocked': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_priorities': True, 'publisher_confirms': True, 'consumer_cancel_notify': True}, 'platform': 'Erlang/OTP', 'version': '3.5.7', 'product': 'RabbitMQ', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'platform': 'Erlang/OTP', 'product': 'RabbitMQ', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'version': '3.5.7', 'cluster_name': 'rabbit@chudik-K501UQ', 'capabilities': {'connection.blocked': True, 'publisher_confirms': True, 'exchange_exchange_bindings': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'consumer_cancel_notify': True, 'basic.nack': True, 'per_consumer_qos': True}, 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
DEBUG:Start from server, version: 0.9, properties: {'cluster_name': 'rabbit@chudik-K501UQ', 'product': 'RabbitMQ', 'capabilities': {'consumer_cancel_notify': True, 'exchange_exchange_bindings': True, 'consumer_priorities': True, 'per_consumer_qos': True, 'authentication_failure_close': True, 'publisher_confirms': True, 'connection.blocked': True, 'basic.nack': True}, 'platform': 'Erlang/OTP', 'version': '3.5.7', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
WARNING:Not Found: /favicon.ico
DEBUG:Start from server, version: 0.9, properties: {'platform': 'Erlang/OTP', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.', 'cluster_name': 'rabbit@chudik-K501UQ', 'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'per_consumer_qos': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True}, 'product': 'RabbitMQ', 'version': '3.5.7'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
WARNING:Not Found: /favicon.ico
DEBUG:Start from server, version: 0.9, properties: {'platform': 'Erlang/OTP', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.', 'product': 'RabbitMQ', 'version': '3.5.7', 'cluster_name': 'rabbit@chudik-K501UQ', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'capabilities': {'basic.nack': True, 'consumer_cancel_notify': True, 'per_consumer_qos': True, 'connection.blocked': True, 'publisher_confirms': True, 'consumer_priorities': True, 'exchange_exchange_bindings': True, 'authentication_failure_close': True}}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
ERROR:Internal Server Error: /songs/profile
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 172, in songID
    song = Song.objects.get(pk=song_id)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 965, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'profile'
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 225, in random
    print(dir.request)
AttributeError: 'builtin_function_or_method' object has no attribute 'request'
WARNING:Not Found: /favicon.ico
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 225, in random
    print(request["mod"])
TypeError: 'WSGIRequest' object is not subscriptable
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 225, in random
    print(request.post["mod"])
AttributeError: 'WSGIRequest' object has no attribute 'post'
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 225, in random
    print(request.method["mod"])
TypeError: string indices must be integers
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 225, in random
    print(request.method.mod)
AttributeError: 'str' object has no attribute 'mod'
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 225, in random
    print(request.POST.get("mod", "type", "genre", "min_diff", "max_diff"))
TypeError: get() takes from 2 to 3 positional arguments but 6 were given
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /9x9.gif
WARNING:Not Found: /PumpManager/9x9.gif
WARNING:Not Found: /PumpManager/9x9.gif
WARNING:Not Found: /index.gif
ERROR:Internal Server Error: /
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 87, in index
    return render(request, 'PumpManager/index.html')
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/templatetags/static.py", line 159, in do_static
    return StaticNode.handle_token(parser, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/templatetags/static.py", line 133, in handle_token
    path = parser.compile_filter(bits[1])
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '/index.gif' from 'PumpManager/index.gif'
ERROR:Internal Server Error: /profile/settings
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 94, in profile_settings
    return render(request, 'PumpManager/profile-settings.html',)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 534, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 3: 'title'. Did you forget to register or load this tag?
WARNING:Not Found: /favicon.ico
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 229, in random
    "versions" : Mix.objects.all()})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 10: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 229, in random
    "versions" : Mix.objects.all()})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 10: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 229, in random
    "versions" : Mix.objects.all()})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 479, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 497, in extend_nodelist
    token, '%r must be the first tag in the template.' % node,
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends "PumpManager/base.html"> must be the first tag in the template.
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 229, in random
    "versions" : Mix.objects.all()})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 229, in random
    "versions" : Mix.objects.all()})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 229, in random
    "versions" : Mix.objects.all()})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 205, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 229, in random
    "versions" : Mix.objects.all()})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 205, in do_block
    raise TemplateSyntaxError("'%s' tag with name '%s' appears more than once" % (bits[0], block_name))
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 245, in random
    if request.Post["min_diff"] != "---" and request.Post["max_diff"] != "---":
AttributeError: 'WSGIRequest' object has no attribute 'Post'
WARNING:Not Found: /favicon.ico
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 258, in random
    res_song_charts = charts[random.randrange(len(charts))]
AttributeError: 'function' object has no attribute 'randrange'
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 259, in random
    result = res_song_charts[randrange(len(res_song_charts))]
TypeError: object of type 'Chart' has no len()
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 259, in random
    result = res_song_charts[randrange(res_song_charts.count())]
AttributeError: 'Chart' object has no attribute 'count'
WARNING:Not Found: /random/songs/144
WARNING:Not Found: /random/songs/359
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 267, in random
    result = res_song_charts[randrange(res_song_charts.count())]
AttributeError: 'Chart' object has no attribute 'count'
WARNING:Not Found: /favicon.ico
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 246, in random
    charts.append(songs.chart_set.filter(type = "C"))
AttributeError: 'QuerySet' object has no attribute 'chart_set'
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 273, in random
    result = res_song_charts[randrange(res_song_charts.count())]
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/random.py", line 186, in randrange
    raise ValueError("empty range for randrange()")
ValueError: empty range for randrange()
ERROR:Internal Server Error: /random/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 273, in random
    result = res_song_charts[randrange(res_song_charts.count())]
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/random.py", line 186, in randrange
    raise ValueError("empty range for randrange()")
ValueError: empty range for randrange()
WARNING:Not Found: /songs/1
WARNING:Not Found: /songs/2
WARNING:Not Found: /songs/5
WARNING:Not Found: /songs/6
WARNING:Not Found: /songs/8
WARNING:Not Found: /songs/9
WARNING:Not Found: /songs/2
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 167, in songs
    return render(request, 'PumpManager/songs.html', {'songs': Song.objects.all()})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 129: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 132, in songs
    raise Exception
Exception
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 131, in songs
    if request.POST.has_key("Update song list"):
AttributeError: 'QueryDict' object has no attribute 'has_key'
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 179, in songs
    'charts': charts,
UnboundLocalError: local variable 'charts' referenced before assignment
WARNING:Not Found: /favicon.ico
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 182, in songs
    {'songs': songs,
UnboundLocalError: local variable 'charts' referenced before assignment
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 129, in songs
    chart.append(song.chart_set.all())
UnboundLocalError: local variable 'chart' referenced before assignment
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 129, in songs
    chart.append(song.chart_set.all())
UnboundLocalError: local variable 'chart' referenced before assignment
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 129, in songs
    chart.append(song.chart_set.all())
UnboundLocalError: local variable 'chart' referenced before assignment
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 177, in songs
    songs.append(chart[0].song.name)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
ERROR:Internal Server Error: /songs/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 177, in songs
    if chart.song.name not in songs:
AttributeError: 'QuerySet' object has no attribute 'song'
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /favicon.ico
WARNING:Not Found: /random/locations
WARNING:Not Found: /random/locations
ERROR:Internal Server Error: /locations/
Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: PumpManager_location.address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/chudik/dbproject/testproj/PumpManager/views.py", line 307, in locations
    return render(request, "PumpManager/locations.html", {"locations": Location.objects.all()})
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/template/defaulttags.py", line 166, in render
    len_values = len(values)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chudik/dbproject/djangoenv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: PumpManager_location.address
DEBUG:Start from server, version: 0.9, properties: {'platform': 'Erlang/OTP', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'capabilities': {'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'basic.nack': True, 'exchange_exchange_bindings': True, 'consumer_cancel_notify': True, 'publisher_confirms': True, 'connection.blocked': True}, 'cluster_name': 'rabbit@chudik-K501UQ', 'version': '3.5.7', 'copyright': 'Copyright (C) 2007-2015 Pivotal Software, Inc.', 'product': 'RabbitMQ'}, mechanisms: ['PLAIN', 'AMQPLAIN'], locales: ['en_US']
DEBUG:Open OK!
DEBUG:using channel_id: 1
DEBUG:Channel open
